mkdir -p NTUPLES
./MakeCompressedNtuple.x -ofile=./NTUPLES/TT_500_327.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Signal/stopdiagonal_500.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/TT_350_177.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Signal/stopdiagonal_350.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/TT_300_127.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Signal/stopdiagonal_300.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/Top.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Top.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/Wjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Wjets.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/Zjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Zjets.root
#./MakeCompressedNtuple.x -ofile=./NTUPLES/Diboson.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/Diboson.root
./MakeCompressedNtuple.x -ofile=./NTUPLES/QCD.root -ifile=/Users/crogan/Dropbox/SAMPLES/SussexNt/QCD.root
